language: ruby
cache: bundler

rvm:
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - 2.4.4
  - 2.5.0
  - 2.5.3

gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

before_install: 'gem install bundler'
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - stex@sterex.de
    on_failure: change
    on_success: never
