language: ruby
cache: bundler

rvm:
  - 2.3.0
  - 2.5.0

env:
  - DISABLE_DATABASE_ENVIRONMENT_CHECK=1

before_install: 'gem install bundler'
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - stex@sterex.de
    on_failure: change
    on_success: never

