language: ruby
cache: bundler

rvm:
  - 2.3.0
  - 2.3.3
  - 2.4.0
  - 2.4.4
  - 2.5.0
  - 2.5.3

before_install: 'gem install bundler'
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - stex@sterex.de
    on_failure: change
    on_success: never

