language: ruby
cache: bundler

rvm:
  - 2.2
  - 2.3

before_install: 'gem install bundler'
script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - stex@sterex.de
    on_failure: change
    on_success: never

